env:
  browser: true
  jquery: true
globals:
  _: true
  io: true
  Phaser: true
  cordova: true
  Promise: true
  ChallengeUtils: true
  PushNotification: true
rules:
  no-console: off
  no-alert: off
extends: airbnb
installedESLint: true
plugins:
  - react
  - jsx-a11y
  - import
