env:
  browser: true
  jquery: true
globals:
  _: true
  Phaser: true
  cordova: true
  ChallengeUtils: true
  PushNotification: true
rules:
  no-console: "off"
  no-alert: "off"
extends: airbnb
installedESLint: true
plugins:
  - react
  - jsx-a11y
  - import
